# Generated by Django 2.1.7 on 2019-03-29 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cpi',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='tier',
            field=models.IntegerField(null=True),
        ),
    ]
