# Generated by Django 2.1.7 on 2019-03-30 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20190329_1541'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='preference_of_professor',
        ),
    ]
