# Generated by Django 2.1.7 on 2019-03-30 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_remove_profile_group_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='group_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='preference_of_professor',
            field=models.ManyToManyField(blank=True, related_name='_profile_preference_of_professor_+', to='login.Profile'),
        ),
    ]
