# Generated by Django 2.1.7 on 2019-04-01 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_auto_20190330_2008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='preference_of_professor',
        ),
    ]
