# Generated by Django 2.1.7 on 2019-04-08 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_auto_20190408_0648'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='pending_join_requests',
        ),
    ]
