# Generated by Django 2.1.7 on 2019-04-01 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('professor', '0001_initial'),
        ('allotment', '0002_auto_20190330_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupinfo',
            name='mentor',
            field=models.ForeignKey(null=django.db.models.deletion.SET_NULL, on_delete=django.db.models.deletion.SET_NULL, to='professor.Professor'),
            preserve_default=django.db.models.deletion.SET_NULL,
        ),
    ]
