# Generated by Django 2.1.7 on 2019-04-08 01:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0003_auto_20190408_0648'),
        ('professor', '0001_initial'),
        ('allotment', '0003_groupinfo_mentor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('group_id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.Batch')),
                ('mentor', models.ForeignKey(null=django.db.models.deletion.SET_NULL, on_delete=django.db.models.deletion.SET_NULL, to='professor.Professor')),
            ],
        ),
        migrations.RemoveField(
            model_name='groupinfo',
            name='mentor',
        ),
        migrations.RemoveField(
            model_name='groupinfo',
            name='user',
        ),
        migrations.DeleteModel(
            name='GroupInfo',
        ),
    ]
