# Generated by Django 2.1.7 on 2019-04-13 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allotment', '0007_auto_20190413_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='preference_of_professor',
            field=models.CharField(default=',', max_length=256),
        ),
    ]
