# Generated by Django 2.1.7 on 2019-04-01 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('professor', '0001_initial'),
        ('administrator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administrator.Admin'),
        ),
        migrations.AddField(
            model_name='batch',
            name='available_professor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='professor.Professor'),
        ),
    ]
