# Generated by Django 2.1.7 on 2019-04-08 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professor', '0001_initial'),
        ('administrator', '0002_auto_20190402_0038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='available_professor',
        ),
        migrations.AddField(
            model_name='batch',
            name='is_preference_filling_allowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='batch',
            name='is_team_formation_allowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='batch',
            name='professor',
            field=models.ManyToManyField(to='professor.Professor'),
        ),
        migrations.AlterField(
            model_name='admin',
            name='branch',
            field=models.CharField(choices=[(1, 'CSED'), (2, 'MED'), (3, 'ChED'), (4, 'CiED'), (5, 'BED'), (6, 'EED'), (7, 'ECED')], max_length=256),
        ),
    ]
