# Generated by Django 2.1.7 on 2019-04-08 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0003_auto_20190408_0648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='branch',
            field=models.SmallIntegerField(choices=[(1, 'CSED'), (2, 'MED'), (3, 'ChED'), (4, 'CiED'), (5, 'BED'), (6, 'EED'), (7, 'ECED')], max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='batch',
            name='professor',
            field=models.ManyToManyField(null=True, to='professor.Professor'),
        ),
    ]
