# Generated by Django 2.1.7 on 2019-04-08 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0004_auto_20190408_0740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='branch',
            field=models.SmallIntegerField(choices=[(1, 'CSED'), (2, 'MED'), (3, 'ChED'), (4, 'CiED'), (5, 'BED'), (6, 'EED'), (7, 'ECED')], null=True),
        ),
    ]
