# Generated by Django 2.1.7 on 2019-04-09 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0005_auto_20190408_0820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='professor',
            field=models.ManyToManyField(to='professor.Professor'),
        ),
    ]
