# Generated by Django 2.1.7 on 2019-04-09 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0006_auto_20190409_0618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='ID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
