# Generated by Django 2.1.7 on 2019-04-12 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0008_batch_professor_data_uploaded'),
    ]

    operations = [
        migrations.RenameField(
            model_name='batch',
            old_name='group_size',
            new_name='number_of_groups',
        ),
    ]
