# Generated by Django 2.1.7 on 2019-04-13 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0009_auto_20190412_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='batch_name',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
