# Generated by Django 2.1.7 on 2019-04-13 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0011_batch_is_mentor_allotted'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='number_of_slots',
            field=models.SmallIntegerField(null=True),
        ),
    ]
