# Generated by Django 2.1.7 on 2019-03-30 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('ID', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=256)),
                ('last_name', models.CharField(max_length=256)),
                ('area_of_interest', models.TextField(null=True)),
            ],
        ),
    ]
