# Generated by Django 2.1.7 on 2019-04-09 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='max_group',
            field=models.SmallIntegerField(default=1),
        ),
    ]
