# Generated by Django 2.1.7 on 2019-04-13 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professor', '0003_auto_20190409_0625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='ID',
            field=models.PositiveSmallIntegerField(primary_key=True, serialize=False),
        ),
    ]
